- name: Configure Docker on EC2 Instances
  hosts: all
  become: true
  tasks:
    - name: Update apt repositories
      apt:
        name: '*'
        state: latest

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker Service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Docker Image
      docker_image:
        name: suvakantanayak/banking
        tag: latest
        source: pull

    - name: Run Docker Container
      docker_container:
        name: financeapp_new
        image: suvakantanaya/banking:latest
        state: started
        ports:
          - "8081:8081"

